import type { Metadata } from "next";
import "./globals.css";
import Header from "./(home)/components/Header";
import CartProvider from "./context/CartContext";
import Footer from "./(home)/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="min-h-screen flex flex-col">
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
